//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source_Control_Final_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {

        public int Id { get; set; }


        [Required(ErrorMessage = "Name is Required")]
        [StringLength(50, MinimumLength = 3,ErrorMessage ="Minimum Length of Name must be 3")]
        public string Name { get; set; }

        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Not a valid Phone number")]
        public string Mobile_Number { get; set; }

        [Required(ErrorMessage = "Email ID is Required")]
        [DataType(DataType.EmailAddress,ErrorMessage ="Enter Email in Proper Format")]
        [MaxLength(50)]
        public string Email { get; set; }


        [Required(ErrorMessage = "Age is Required")]
        [Range(21, 100, ErrorMessage = "Age must be between 21-100 in years.")]
        public string Age { get; set; }

        [Required(ErrorMessage = "Pincode is Required")]
        [RegularExpression(@"^([0-9]{6})$", ErrorMessage = "Not a valid Pincode")]
        public string Pincode { get; set; }

        [Required(ErrorMessage = "City is Required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Minimum Length of City must be 3")]
        public string City { get; set; }

        [Required(ErrorMessage = "Username is Required")]
        [RegularExpression(@"^([a-zA-Z0-9]{6,18})$", ErrorMessage = "Username must be Alphanumeric with length of 6-18")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password is Required")]
        [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$", ErrorMessage = "Password Must Contain Minimum eight characters, at least one letter, one number and one special character")]
        public string Password { get; set; }
    }
}
