//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_List
    {
        public int Product_Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public string Short_Desc { get; set; }
        public string Long_Desc { get; set; }
        public string Small_Image_path { get; set; }
        public string Lage_Image_path { get; set; }
        public string Category { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
